wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.15.8
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719878900.222896
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.11.7
      5: 0.15.8
      8:
      - 1
      - 4
      - 5
