wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719879165.0
    t:
      1:
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.6
      5: 0.16.6
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    framework: huggingface
