wandb_version: 1

learning_rate:
  desc: null
  value: 0.15
architecture:
  desc: null
  value: BERT
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 250
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719916252.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.10.6
      5: 0.16.6
      6: 4.39.3
      8:
      - 4
      - 5
      13: darwin-arm64
