wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: BERT
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 500
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719785090.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      - 24
      4: 3.10.12
      5: 0.16.6
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
